spring:
    datasource:
        url: ${SQL_URL}
        username: ${SQL_USER}
        password: ${SQL_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
    show-sql: false
    properties:
        hibernate:
            format_sql: false

server:
    error:
        include-stacktrace: never

logging:
  level:
    org.springframework.security.web: DEBUG
